FROM fishtownanalytics/dbt:1.0.0

ENV DATABASE_NAME priceloop
ENV DATABASE_USERNAME postgres
ENV DATABASE_PASSWORD test3
ENV DATABASE_HOST localhost
ENV DATABASE_PORT 5432

WORKDIR /usr/app/dbt/
COPY requirement.txt ./requirement.txt 
RUN pip3 install -r requirement.txt

ENTRYPOINT [ "/bin/bash", "-c" ]