amazon:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: "localhost"
      port: 5432
      user: "postgres"
      pass: "test3"
      dbname: "priceloop"
      schema: "{{ env_var('DATABASE_SCHEMA', var('database_schema', '')) }}"