version: 2

models:
  - name: product
    description: Customer data
    config:
      materialized: table
      unique_key: "{{ env_var('UNIQUE_KEY', var('unique_key', '')) }}"
    meta:
      fal:
        scripts:
          before:
            - fal_scripts/script.py